### ISSUE TITLE
安装包在哪里呀？

### ISSUE THREAD

**Issue by liuwenwu520** [HarekazeQF/PhantomAIBOX#1]
安装包在哪里呀？找了半天也没有找到地址。

**Comment by GUANXINPENG** [comment]
好像作者没发release。
https://www.bilibili.com/video/BV1Vc411T7Nw/?vd_source=b37c3e1783f85e2737d6e01b159e9f0c
简介里的百度网盘

**Comment by liuwenwu520** [comment]
> 好像作者没发release。 https://www.bilibili.com/video/BV1Vc411T7Nw/?vd_source=b37c3e1783f85e2737d6e01b159e9f0c 简介里的百度网盘

谢谢
